                
/* creazione database */

                CREATE TABLE venditore(
				    id_v INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				    nome VARCHAR(128),
				    cognome VARCHAR(128),
				    username VARCHAR(128),
				    password VARCHAR(128),
				    indirizzo VARCHAR(128),
				    residenza VARCHAR(128),
				    email VARCHAR(128),
				    saldo DOUBLE);


		CREATE TABLE cliente(
				    id_c INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				    nome VARCHAR(128),
				    cognome VARCHAR(128),
				    username VARCHAR(128),
				    password VARCHAR(128),
				    indirizzo VARCHAR(128),
				    residenza VARCHAR(128),
				    email VARCHAR(128),
				    saldo DOUBLE);


		CREATE TABLE oggetto(
				    id_o INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				    nome VARCHAR(128),
				    descrizione VARCHAR(128),
				    prezzo DOUBLE,
				    quantita INTEGER, 
                                    foto VARCHAR(128),
                                    id_venditore INTEGER,
                                    FOREIGN KEY (id_venditore) REFERENCES venditore (id_v));

                CREATE TABLE acquisto(
				    id_a INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    id_compratore INTEGER,
                                    id_oggetto INTEGER,
                                    FOREIGN KEY (id_oggetto) REFERENCES oggetto(id_o),
                                    FOREIGN KEY (id_compratore) REFERENCES cliente(id_c));



/* popolazione database */

INSERT INTO venditore(nome, cognome, username, password, indirizzo, residenza, email, saldo)
VALUES ('Matteo', 'Cabiddu', 'matteo', 'matteocabiddu', 'Via Cagliari, 4', 'Assemini', 'matteocabiddu@gmail.com', 500),
	('Mattia', 'Caboni', 'mattia', 'mattiacaboni', 'Via Oristano, 4', 'Assemini', 'mattiacaboni@gmail.com', 400),
        ('Nicola', 'Diana', 'nicola', 'nicoladiana', 'Via Ponte, 29', 'Elmas', 'nicoladiana@gmail.com', 600),
	('Paolo', 'Corpino', 'paolo', 'paolocorpino', 'Via Quadri, 38', 'Decimomannu', 'paolocorpino@gmail.com', 350);


INSERT INTO cliente(nome, cognome, username, password, indirizzo, residenza, email, saldo)
VALUES ('Alberto', 'Cabiddu', 'alberto', 'albertocabiddu', 'Via Cagliari, 4', 'Assemini', 'albertocabiddu@gmail.com', 300),
	('Claudio', 'Caboni', 'claudio', 'claudiocaboni', 'Via Oristano, 4', 'Assemini', 'claudiocaboni@gmail.com', 400),
        ('Davide', 'Diana', 'davide', 'davidediana', 'Via Ponte, 29', 'Elmas', 'nicoladiana@gmail.com', 60),
	('Ettore', 'Corpino', 'ettore', 'ettorecorpino', 'Via Quadri, 38', 'Decimomannu', 'ettorecorpino@gmail.com', 600);




INSERT INTO oggetto(nome, descrizione, foto, prezzo, quantita, id_venditore)
VALUES ('HP pavilion x2 210', 'Convertibile HP 10 pollici', 'foto/hp.jpg', 299.99, 20, 1),
	('Asus T100 Chi', 'Convertibile Asus 10 pollici', 'foto/Asus.jpg', 399.99, 30, 2),
	('Acer switch 10', 'Convertibile Acer 10 pollici', 'foto/Acer.jpg', 279.99, 15, 3),
	('Hp active pen 230', 'Active pen Hp', 'foto/Pen_Hp.jpg', 49.99, 40, 4);

